import { RelatedTools } from "@/app/tools/[...toolId]/Relatedtools";
import { serverConfig } from "@/config/server";

const TOOL_PATH = "/tools/calculator/sip-calculator";
const TOOL_URL = `${serverConfig.siteUrl.replace(/\/+$/, "")}${TOOL_PATH}`;

const LAST_REVIEWED = "August 2026";

const faqItems = [
  {
    q: "What is a SIP calculator?",
    a: "A SIP calculator is a financial planning tool that estimates the future value of regular investments made through a Systematic Investment Plan. It can help estimate the invested amount, potential returns, and total maturity value based on the monthly investment, investment period, and expected return rate.",
  },
  {
    q: "What is SIP?",
    a: "SIP stands for Systematic Investment Plan. It is a method of investing a fixed amount at regular intervals, commonly monthly, into a mutual fund or other eligible investment product. SIPs help investors invest regularly instead of trying to time the market.",
  },
  {
    q: "How does a SIP calculator work?",
    a: "A SIP calculator generally uses the monthly investment amount, investment duration, and expected annual return to estimate the future value of the investment. The result is an illustration based on the assumptions entered and is not a guarantee of actual investment returns.",
  },
  {
    q: "What is the SIP formula?",
    a: "A commonly used SIP future-value formula is FV = P × [((1 + r)^n − 1) ÷ r] × (1 + r), where P is the periodic investment, r is the periodic rate of return, and n is the total number of investment periods. The exact calculation can vary depending on the assumed investment timing and calculator methodology.",
  },
  {
    q: "How much will I get from a ₹5,000 monthly SIP?",
    a: "The maturity value of a ₹5,000 monthly SIP depends on the investment duration and assumed return rate. For example, a longer investment period can allow more time for compounding, while the actual return earned by an investment may differ from the assumed rate used by the calculator.",
  },
  {
    q: "How much should I invest in SIP every month?",
    a: "The appropriate SIP amount depends on your income, expenses, financial goals, investment horizon, existing savings, risk tolerance, and expected return. A SIP calculator can be used to work backward from a target amount and estimate the monthly investment that may be required under selected assumptions.",
  },
  {
    q: "Can I use a SIP calculator for mutual funds?",
    a: "Yes. SIP calculators are commonly used to estimate potential outcomes from recurring mutual fund investments. The calculation is based on the investment amount, time period, and assumed rate of return.",
  },
  {
    q: "What is SIP maturity value?",
    a: "SIP maturity value is the estimated total value of the investment at the end of the selected investment period. It generally includes the amount invested plus the estimated investment returns.",
  },
  {
    q: "What is the difference between invested amount and maturity value?",
    a: "The invested amount is the total money contributed during the SIP period. The maturity value is the estimated value of the investment at the end of the period, including the potential returns generated on the investments.",
  },
  {
    q: "What is SIP return?",
    a: "SIP return is the gain generated by the investments made through a systematic investment plan. A calculator may estimate the return based on an assumed annual rate, but actual mutual fund returns can fluctuate and are not guaranteed.",
  },
  {
    q: "What is XIRR in SIP?",
    a: "XIRR is a method used to calculate an annualized return when investments or cash flows occur on different dates. Because SIP investments are made periodically, XIRR can be useful when evaluating actual historical SIP cash flows.",
  },
  {
    q: "What is step-up SIP?",
    a: "A step-up SIP increases the investment amount periodically, such as increasing the monthly contribution by a fixed percentage or amount each year. Increasing contributions as income grows can potentially help investors build a larger investment corpus over time.",
  },
  {
    q: "What is the benefit of increasing SIP every year?",
    a: "Increasing the SIP contribution over time can increase the total amount invested and potentially increase the maturity value. A step-up strategy can also help align investment contributions with increasing income.",
  },
  {
    q: "Can I change my SIP amount?",
    a: "Many SIP investment plans allow investors to modify, pause, increase, or stop contributions subject to the rules of the investment provider and product. A SIP calculator can help compare different contribution levels before making a change.",
  },
  {
    q: "Is SIP better than lump-sum investment?",
    a: "SIP and lump-sum investing are different investment approaches. SIP spreads investments over time, while lump-sum investing deploys a larger amount at once. Which approach is suitable depends on available capital, investment horizon, market conditions, financial goals, and risk tolerance.",
  },
  {
    q: "Does SIP guarantee returns?",
    a: "No. SIP itself is an investment method and does not guarantee returns. The value of a mutual fund investment can rise or fall depending on the performance of the underlying investments and market conditions.",
  },
  {
    q: "How does compounding work in SIP?",
    a: "Compounding allows investment returns to generate further potential returns over time. With regular SIP contributions, earlier investments have more time to compound, which is one reason longer investment horizons can have a significant effect on the estimated maturity value.",
  },
  {
    q: "How long should I invest through SIP?",
    a: "The appropriate SIP duration depends on the financial goal. Long-term goals may benefit from longer investment horizons because they provide more time for contributions and potential compounding. The investment period should be aligned with the goal and risk profile.",
  },
  {
    q: "Is a SIP calculator free?",
    a: "Yes. This SIP calculator is free to use for estimating potential SIP investment outcomes based on the assumptions entered.",
  },
  {
    q: "Does the SIP calculator work on mobile?",
    a: "Yes. The SIP calculator page is designed to work across mobile, tablet, and desktop screen sizes.",
  },
  {
    q: "Are SIP calculator results guaranteed?",
    a: "No. SIP calculator results are estimates based on the investment amount, duration, and assumed return rate. Actual investment performance can differ materially from the assumptions used in the calculation.",
  },
  {
    q: "How often should I review my SIP?",
    a: "SIP investments should be reviewed periodically and whenever there are significant changes in income, financial goals, risk tolerance, investment horizon, or overall financial circumstances.",
  },
];

const howToSteps = [
  {
    title: "Enter your monthly SIP amount",
    desc: "Enter the amount you plan to invest regularly through your SIP. This is the periodic contribution used in the calculation.",
  },
  {
    title: "Choose your investment period",
    desc: "Enter the number of years you expect to continue investing. A longer investment horizon can provide more time for potential compounding.",
  },
  {
    title: "Enter an expected return",
    desc: "Enter an assumed annual rate of return for the calculation. The assumption should be realistic and should not be treated as a guaranteed return.",
  },
  {
    title: "Calculate your estimated value",
    desc: "Use the calculator to estimate your total invested amount, potential returns, and estimated maturity value.",
  },
  {
    title: "Compare different SIP amounts",
    desc: "Try different monthly investment amounts to understand how increasing or decreasing your SIP contribution can affect the estimated result.",
  },
  {
    title: "Compare different time periods",
    desc: "Test different investment horizons to see how the duration of your SIP affects the potential maturity value.",
  },
  {
    title: "Review your investment plan",
    desc: "Review your SIP periodically and update your contribution when your income, goals, or financial circumstances change.",
  },
];

const coreFeatures = [
  {
    title: "SIP Investment Calculator",
    desc: "Estimate the potential future value of regular monthly SIP investments using your selected investment period and return assumption.",
    icon: "💰",
  },
  {
    title: "SIP Return Calculation",
    desc: "Estimate potential investment returns separately from the total amount contributed through the SIP.",
    icon: "📈",
  },
  {
    title: "Maturity Value",
    desc: "Estimate the potential value of your SIP investment at the end of the selected investment period.",
    icon: "🎯",
  },
  {
    title: "Monthly Investment Planning",
    desc: "Explore how different monthly SIP contributions can affect your potential investment outcome.",
    icon: "🧮",
  },
  {
    title: "Compounding Illustration",
    desc: "Understand how investment duration and regular contributions can influence potential wealth accumulation.",
    icon: "📊",
  },
  {
    title: "Step-Up SIP Planning",
    desc: "Use increasing SIP contributions as a planning concept to understand how higher future investments may affect long-term outcomes.",
    icon: "⬆️",
  },
  {
    title: "Goal-Based SIP Planning",
    desc: "Compare SIP contributions against a target amount to understand how much you may need to invest regularly.",
    icon: "🎯",
  },
  {
    title: "Responsive Calculator",
    desc: "Use the SIP calculator across mobile, tablet, and desktop devices.",
    icon: "📱",
  },
];

const audiences = [
  {
    title: "First-Time Investors",
    desc: "Understand how regular investments can potentially grow over a selected period.",
    icon: "🌱",
  },
  {
    title: "Mutual Fund Investors",
    desc: "Estimate potential SIP maturity values using different investment and return assumptions.",
    icon: "📊",
  },
  {
    title: "Working Professionals",
    desc: "Plan a monthly investment amount that fits within your regular income and long-term goals.",
    icon: "👔",
  },
  {
    title: "Goal-Based Investors",
    desc: "Estimate the SIP contribution that may be required to work toward a long-term financial target.",
    icon: "🎯",
  },
  {
    title: "Long-Term Investors",
    desc: "Explore how investment duration and regular contributions can affect potential wealth accumulation.",
    icon: "📈",
  },
  {
    title: "Indian Investors",
    desc: "Use INR-based SIP examples for common investment-planning scenarios in India.",
    icon: "🇮🇳",
  },
];

const sipEducation = [
  {
    title: "What Is a SIP?",
    body: "A Systematic Investment Plan is a method of investing a fixed amount at regular intervals, commonly monthly. SIPs can help investors maintain a disciplined investment habit without needing to invest a large amount at once.",
  },
  {
    title: "How Does SIP Work?",
    body: "Under a SIP, a predetermined amount is invested at regular intervals. Depending on the investment product, the contribution purchases units or other investment interests at the applicable price. The value of the investment changes as the underlying assets change in value.",
  },
  {
    title: "SIP and Compounding",
    body: "Compounding occurs when investment returns remain invested and can themselves generate further returns. Earlier contributions generally have more time to compound, which can make investment duration an important factor in long-term SIP planning.",
  },
  {
    title: "SIP Return",
    body: "SIP return depends on the performance of the underlying investment. A calculator typically uses an assumed annual return to create an illustration. Actual returns can be higher or lower than the assumption.",
  },
  {
    title: "Step-Up SIP",
    body: "A step-up SIP increases the periodic investment amount over time. For example, an investor might increase their monthly SIP contribution by 10% each year as their income increases.",
  },
  {
    title: "SIP vs Lump Sum",
    body: "SIP involves investing smaller amounts at regular intervals, while lump-sum investing involves deploying a larger amount at once. Both approaches have different cash-flow and market-exposure characteristics.",
  },
  {
    title: "SIP and Rupee-Cost Averaging",
    body: "Regular investing can result in purchasing more units when prices are lower and fewer units when prices are higher, assuming the investment amount remains fixed. This is commonly associated with rupee-cost averaging, although it does not eliminate investment risk.",
  },
  {
    title: "Long-Term SIP Investing",
    body: "A longer investment horizon gives regular contributions more time to potentially grow and compound. However, longer periods also mean that actual outcomes remain exposed to market performance and changing economic conditions.",
  },
];

const sipMistakes = [
  "Choosing an unrealistic return assumption.",
  "Stopping a long-term SIP solely because of short-term market volatility.",
  "Investing without defining a financial goal or time horizon.",
  "Failing to increase the SIP amount as income grows.",
  "Ignoring fees, taxes, and the actual characteristics of the investment product.",
  "Treating a calculator projection as a guaranteed investment outcome.",
];

const sipStrategies = [
  "Start with an investment amount that is sustainable for your budget.",
  "Increase your SIP periodically when your income increases.",
  "Match the investment horizon with the financial goal.",
  "Use realistic return assumptions when making projections.",
  "Diversify investments according to your financial goals and risk tolerance.",
  "Review the SIP periodically rather than reacting to every short-term market movement.",
];

const sipExamples = [
  {
    monthly: "₹1,000",
    years: "10 years",
    invested: "₹1.2 lakh",
    corpus: "Depends on return assumption",
  },
  {
    monthly: "₹5,000",
    years: "10 years",
    invested: "₹6 lakh",
    corpus: "Depends on return assumption",
  },
  {
    monthly: "₹10,000",
    years: "15 years",
    invested: "₹18 lakh",
    corpus: "Depends on return assumption",
  },
  {
    monthly: "₹20,000",
    years: "20 years",
    invested: "₹48 lakh",
    corpus: "Depends on return assumption",
  },
];

const factors = [
  {
    title: "Monthly Investment",
    desc: "A higher monthly SIP contribution generally increases the total amount invested and can increase the estimated maturity value.",
  },
  {
    title: "Investment Duration",
    desc: "A longer investment period gives contributions more time to potentially grow and compound.",
  },
  {
    title: "Expected Return",
    desc: "The assumed annual return has a significant effect on the estimated future value. Actual returns can differ from the assumption.",
  },
  {
    title: "Step-Up Contributions",
    desc: "Increasing the SIP contribution over time can increase the total investment and potential future value.",
  },
  {
    title: "Market Performance",
    desc: "Actual investment results depend on the performance of the underlying assets and can fluctuate over time.",
  },
  {
    title: "Fees and Taxes",
    desc: "Investment costs and applicable taxes can reduce the actual amount received compared with a simple calculator projection.",
  },
];

export default function SipCalculatorSeoContent() {
  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: serverConfig.siteUrl,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Tools",
        item: `${serverConfig.siteUrl}/tools`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "SIP Calculator",
        item: TOOL_URL,
      },
    ],
  };

  return (
    <div className="mx-auto max-w-6xl space-y-12 px-4 py-8 text-white">
      {/* Breadcrumb structured data only. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbSchema),
        }}
      />

      {/* Primary Intent */}
      <section aria-labelledby="sip-intro-heading" className="space-y-4">
        <p className="text-sm font-medium text-blue-300">
          Savings • SIP • Mutual Funds • Investment Planning
        </p>

        <h2
          id="sip-intro-heading"
          className="text-3xl font-bold tracking-tight sm:text-4xl"
        >
          SIP Calculator for Investment, Returns and Maturity Value
        </h2>

        <p className="max-w-4xl text-sm leading-7 text-white/70 sm:text-base">
          Use this SIP calculator to estimate the potential future value of
          regular investments, total amount invested, and estimated investment
          returns. Enter your monthly SIP amount, investment duration, and
          expected annual return to compare different savings and investment
          scenarios.
        </p>

        <p className="max-w-4xl text-sm leading-7 text-white/60 sm:text-base">
          The calculator provides an estimate based on the assumptions you
          enter. Actual investment returns can vary because of market
          performance, fees, taxes, investment selection, and other factors.
          Calculator results should therefore be treated as illustrations
          rather than guaranteed outcomes.
        </p>
      </section>

      {/* Features */}
      <section
        aria-labelledby="features-heading"
        className="space-y-4"
      >
        <h2
          id="features-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Calculator Features
        </h2>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {coreFeatures.map((item) => (
            <article
              key={item.title}
              className="rounded-2xl border border-white/10 bg-white/5 p-5"
            >
              <div className="text-2xl" aria-hidden="true">
                {item.icon}
              </div>

              <h3 className="mt-3 text-sm font-semibold">
                {item.title}
              </h3>

              <p className="mt-2 text-xs leading-6 text-white/65">
                {item.desc}
              </p>
            </article>
          ))}
        </div>
      </section>

      {/* How To */}
      <section
        aria-labelledby="howto-heading"
        className="space-y-4"
      >
        <h2
          id="howto-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          How to Use the SIP Calculator
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          {howToSteps.map((step, index) => (
            <article
              key={step.title}
              className="rounded-2xl border border-white/10 bg-white/5 p-5"
            >
              <div className="flex items-start gap-3">
                <div
                  className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-white text-sm font-bold text-black"
                  aria-hidden="true"
                >
                  {index + 1}
                </div>

                <div>
                  <h3 className="text-sm font-semibold">
                    {step.title}
                  </h3>

                  <p className="mt-1 text-xs leading-6 text-white/65">
                    {step.desc}
                  </p>
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* Audience */}
      <section
        aria-labelledby="audience-heading"
        className="space-y-4"
      >
        <h2
          id="audience-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Who Should Use a SIP Calculator?
        </h2>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {audiences.map((item) => (
            <article
              key={item.title}
              className="rounded-2xl border border-white/10 bg-white/5 p-5"
            >
              <div className="text-2xl" aria-hidden="true">
                {item.icon}
              </div>

              <h3 className="mt-3 text-sm font-semibold">
                {item.title}
              </h3>

              <p className="mt-2 text-xs leading-6 text-white/65">
                {item.desc}
              </p>
            </article>
          ))}
        </div>
      </section>

      {/* Formula */}
      <section
        aria-labelledby="formula-heading"
        className="space-y-4"
      >
        <h2
          id="formula-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Calculator Formula
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              SIP Future Value Formula
            </h3>

            <p className="mt-3 text-xs leading-6 text-white/65">
              A commonly used SIP calculation estimates the future value of
              periodic investments using the investment amount, periodic
              return, and number of investment periods.
            </p>

            <div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4">
              <p className="font-medium text-white">
                FV = P × [((1 + r)ⁿ − 1) ÷ r] × (1 + r)
              </p>
            </div>

            <h4 className="mt-5 text-sm font-semibold">
              Variables
            </h4>

            <ul className="mt-3 space-y-2 text-xs leading-6 text-white/65">
              <li>
                <strong className="text-white">P:</strong>{" "}
                Periodic SIP investment amount.
              </li>

              <li>
                <strong className="text-white">r:</strong>{" "}
                Periodic rate of return.
              </li>

              <li>
                <strong className="text-white">n:</strong>{" "}
                Total number of investment periods.
              </li>

              <li>
                <strong className="text-white">FV:</strong>{" "}
                Estimated future value of the SIP investment.
              </li>
            </ul>

            <p className="mt-5 text-xs leading-6 text-white/65">
              The exact formula can differ depending on whether investments
              are assumed to occur at the beginning or end of each period.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              SIP Investment and Return
            </h3>

            <p className="mt-3 text-xs leading-6 text-white/65">
              The total amount invested through a regular monthly SIP can be
              calculated by multiplying the monthly contribution by the
              number of months.
            </p>

            <div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4">
              <p className="font-medium text-white">
                Total Invested = Monthly SIP × Number of Months
              </p>
            </div>

            <p className="mt-4 text-xs leading-6 text-white/65">
              The estimated investment gain can then be viewed as the
              difference between the estimated maturity value and the total
              amount invested.
            </p>

            <div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4">
              <p className="font-medium text-white">
                Estimated Gain = Maturity Value − Total Invested
              </p>
            </div>
          </article>
        </div>
      </section>

      {/* Methodology */}
      <section
        aria-labelledby="methodology-heading"
        className="space-y-4"
      >
        <h2
          id="methodology-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Calculator Methodology
        </h2>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
          <p className="text-xs leading-7 text-white/65 sm:text-sm">
            This calculator uses the assumptions entered by the user to
            estimate the potential future value of regular SIP investments.
            The calculation is scenario-based, meaning that changing the
            monthly investment, investment period, or expected return can
            materially change the result.
          </p>

          <p className="mt-4 text-xs leading-7 text-white/65 sm:text-sm">
            The estimated maturity value should therefore be interpreted as a
            projection under a specific set of assumptions rather than a
            prediction of actual investment performance.
          </p>

          <p className="mt-4 text-xs leading-7 text-white/65 sm:text-sm">
            Actual mutual fund and market-linked investment returns can
            fluctuate. The calculator does not eliminate investment risk or
            guarantee a particular maturity value.
          </p>
        </div>
      </section>

      {/* Assumptions */}
      <section
        aria-labelledby="assumptions-heading"
        className="space-y-4"
      >
        <h2
          id="assumptions-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Calculator Assumptions
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Monthly Investment
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              The monthly investment is the amount assumed to be contributed
              regularly to the SIP. Increasing the monthly contribution
              generally increases the estimated future value.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Investment Period
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              The investment period determines how long regular contributions
              remain invested. A longer period can provide more time for
              potential growth and compounding.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Expected Return
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              The expected return is an assumed annual rate used to estimate
              the future value. It is not a guaranteed return and should be
              selected carefully.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Investment Frequency
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              SIPs are commonly structured as monthly investments, although
              other frequencies may be available depending on the investment
              product.
            </p>
          </article>
        </div>
      </section>

      {/* Education */}
      <section
        aria-labelledby="education-heading"
        className="space-y-6"
      >
        <h2
          id="education-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Investment Education
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          {sipEducation.map((item) => (
            <article
              key={item.title}
              className="rounded-2xl border border-white/10 bg-white/5 p-5"
            >
              <h3 className="text-sm font-semibold">
                {item.title}
              </h3>

              <p className="mt-2 text-xs leading-6 text-white/65">
                {item.body}
              </p>
            </article>
          ))}
        </div>
      </section>

      {/* Step Up */}
      <section
        aria-labelledby="stepup-heading"
        className="space-y-4"
      >
        <h2
          id="stepup-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Step-Up SIP Calculator
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              What Is Step-Up SIP?
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              A step-up SIP increases the amount invested periodically. For
              example, an investor starting with a ₹10,000 monthly SIP might
              increase the contribution by a fixed percentage each year as
              their income increases.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Why Increase Your SIP?
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              Increasing contributions can help investors direct more of their
              growing income toward long-term financial goals. It can also
              increase the total amount invested and potential future value,
              subject to investment performance.
            </p>
          </article>
        </div>
      </section>

      {/* Comparison */}
      <section
        aria-labelledby="comparison-heading"
        className="space-y-4"
      >
        <h2
          id="comparison-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP vs Lump-Sum Investment
        </h2>

        <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5">
          <table className="w-full min-w-[640px] text-left text-sm">
            <caption className="sr-only">
              Comparison between SIP and lump-sum investing
            </caption>

            <thead className="border-b border-white/10">
              <tr>
                <th scope="col" className="p-4">
                  Planning Area
                </th>

                <th scope="col" className="p-4">
                  SIP
                </th>

                <th scope="col" className="p-4">
                  Lump Sum
                </th>
              </tr>
            </thead>

            <tbody>
              <tr className="border-b border-white/5">
                <th scope="row" className="p-4 font-medium">
                  Investment style
                </th>

                <td className="p-4 text-white/65">
                  Regular investments over time.
                </td>

                <td className="p-4 text-white/65">
                  Larger amount invested at one time.
                </td>
              </tr>

              <tr className="border-b border-white/5">
                <th scope="row" className="p-4 font-medium">
                  Cash flow
                </th>

                <td className="p-4 text-white/65">
                  Suitable for regular income-based investing.
                </td>

                <td className="p-4 text-white/65">
                  Requires capital to be available upfront.
                </td>
              </tr>

              <tr className="border-b border-white/5">
                <th scope="row" className="p-4 font-medium">
                  Market exposure
                </th>

                <td className="p-4 text-white/65">
                  Investment is spread across multiple contribution dates.
                </td>

                <td className="p-4 text-white/65">
                  A larger amount is exposed to the market at the investment
                  date.
                </td>
              </tr>

              <tr>
                <th scope="row" className="p-4 font-medium">
                  Common use
                </th>

                <td className="p-4 text-white/65">
                  Regular long-term investing.
                </td>

                <td className="p-4 text-white/65">
                  Deploying existing available capital.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Examples */}
      <section
        aria-labelledby="examples-heading"
        className="space-y-4"
      >
        <h2
          id="examples-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Investment Examples
        </h2>

        <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5">
          <table className="w-full min-w-[600px] text-left text-sm">
            <caption className="sr-only">
              Illustrative SIP investment amounts and periods
            </caption>

            <thead className="border-b border-white/10">
              <tr>
                <th scope="col" className="p-4">
                  Monthly SIP
                </th>

                <th scope="col" className="p-4">
                  Investment Period
                </th>

                <th scope="col" className="p-4">
                  Total Invested
                </th>

                <th scope="col" className="p-4">
                  Estimated Corpus
                </th>
              </tr>
            </thead>

            <tbody>
              {sipExamples.map((item) => (
                <tr
                  key={`${item.monthly}-${item.years}`}
                  className="border-b border-white/5 last:border-0"
                >
                  <td className="p-4">
                    {item.monthly}
                  </td>

                  <td className="p-4">
                    {item.years}
                  </td>

                  <td className="p-4">
                    {item.invested}
                  </td>

                  <td className="p-4">
                    {item.corpus}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="text-xs leading-6 text-white/65">
          These examples show the contribution amount only. The actual
          maturity value depends on the return assumption and investment
          performance. They should not be interpreted as expected or
          guaranteed returns.
        </p>
      </section>

      {/* Goal Based */}
      <section
        aria-labelledby="goal-heading"
        className="space-y-4"
      >
        <h2
          id="goal-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Goal-Based SIP Planning
        </h2>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
          <p className="text-xs leading-7 text-white/65 sm:text-sm">
            SIPs can be used for a wide range of long-term financial goals,
            such as education, home purchase, wealth accumulation, travel,
            emergency reserves, or other planned expenses. A goal-based
            approach starts with the target amount and time horizon and then
            estimates the periodic investment that may be required.
          </p>

          <p className="mt-4 text-xs leading-7 text-white/65 sm:text-sm">
            Because investment returns are uncertain, it can be useful to
            compare conservative, base-case, and higher-return scenarios
            instead of relying on one assumed rate.
          </p>
        </div>
      </section>

      {/* Factors */}
      <section
        aria-labelledby="factors-heading"
        className="space-y-4"
      >
        <h2
          id="factors-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Factors That Affect SIP Returns
        </h2>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {factors.map((item) => (
            <article
              key={item.title}
              className="rounded-2xl border border-white/10 bg-white/5 p-5"
            >
              <h3 className="text-sm font-semibold">
                {item.title}
              </h3>

              <p className="mt-2 text-xs leading-6 text-white/65">
                {item.desc}
              </p>
            </article>
          ))}
        </div>
      </section>

      {/* India */}
      <section
        aria-labelledby="india-heading"
        className="space-y-4"
      >
        <h2
          id="india-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Investment Planning in India
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              SIP in India
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              SIP investing is commonly used by Indian investors for regular
              mutual fund investments. Investors can choose contribution
              amounts and investment horizons based on their financial goals,
              income, and risk tolerance.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              SIP and Inflation
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              Inflation reduces the purchasing power of money over time. When
              setting a long-term investment target, consider whether the
              future cost of the goal may be higher than its current cost.
            </p>
          </article>
        </div>
      </section>

      {/* Results */}
      <section
        aria-labelledby="results-heading"
        className="space-y-4"
      >
        <h2
          id="results-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          How to Interpret SIP Calculator Results
        </h2>

        <div className="grid gap-4 md:grid-cols-3">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Total Invested
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              This is the total amount contributed through the SIP over the
              selected investment period.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Estimated Returns
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              This represents the estimated gain based on the return
              assumption entered into the calculator.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Estimated Maturity Value
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              This is the estimated total value of the investment, combining
              the amount invested and the projected returns.
            </p>
          </article>
        </div>
      </section>

      {/* Mistakes */}
      <section
        aria-labelledby="mistakes-heading"
        className="space-y-4"
      >
        <h2
          id="mistakes-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Common SIP Investment Mistakes
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Mistakes to Avoid
            </h3>

            <ul className="mt-3 space-y-2 text-xs leading-6 text-white/65">
              {sipMistakes.map((item) => (
                <li key={item}>
                  {item}
                </li>
              ))}
            </ul>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Better SIP Practices
            </h3>

            <ul className="mt-3 space-y-2 text-xs leading-6 text-white/65">
              {sipStrategies.map((item) => (
                <li key={item}>
                  {item}
                </li>
              ))}
            </ul>
          </article>
        </div>
      </section>

      {/* Long Term */}
      <section
        aria-labelledby="longterm-heading"
        className="space-y-4"
      >
        <h2
          id="longterm-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Long-Term SIP Investing
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Power of Time
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              Time can be an important factor in long-term investing because
              earlier contributions have more time to potentially compound.
              Extending the investment horizon can therefore materially affect
              a SIP projection.
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <h3 className="text-sm font-semibold">
              Consistent Investing
            </h3>

            <p className="mt-2 text-xs leading-6 text-white/65">
              Regular investing can create a disciplined savings habit.
              However, consistency does not remove market risk, and investors
              should choose investments appropriate for their objectives and
              risk tolerance.
            </p>
          </article>
        </div>
      </section>

      {/* Limitations */}
      <section
        aria-labelledby="limitations-heading"
        className="space-y-4"
      >
        <h2
          id="limitations-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          SIP Calculator Limitations
        </h2>

        <div className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-6">
          <ul className="space-y-3 text-xs leading-6 text-white/70 sm:text-sm">
            <li>
              Results are estimates based on the inputs and assumptions used.
            </li>

            <li>
              Investment returns are not guaranteed and actual market
              performance can differ from projections.
            </li>

            <li>
              SIP calculations generally use a constant assumed rate of
              return, while actual investment returns can vary over time.
            </li>

            <li>
              Taxes, fees, exit loads, and other investment costs may affect
              actual returns.
            </li>

            <li>
              A calculator projection does not account for every possible
              market or personal financial circumstance.
            </li>

            <li>
              The calculator should be used for educational and planning
              purposes rather than as a guarantee of future financial results.
            </li>
          </ul>
        </div>
      </section>

      {/* Methodology / Review */}
      <section
        aria-labelledby="review-heading"
        className="space-y-4"
      >
        <h2
          id="review-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Methodology and Review Information
        </h2>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
          <dl className="grid gap-5 sm:grid-cols-2">
            <div>
              <dt className="text-xs font-semibold uppercase tracking-wide text-white/50">
                Methodology
              </dt>

              <dd className="mt-1 text-sm text-white/75">
                Scenario-based SIP investment calculations using the
                assumptions entered into the calculator.
              </dd>
            </div>

            <div>
              <dt className="text-xs font-semibold uppercase tracking-wide text-white/50">
                Last reviewed
              </dt>

              <dd className="mt-1 text-sm text-white/75">
                {LAST_REVIEWED}
              </dd>
            </div>

            <div>
              <dt className="text-xs font-semibold uppercase tracking-wide text-white/50">
                Purpose
              </dt>

              <dd className="mt-1 text-sm text-white/75">
                Educational and investment-planning estimation.
              </dd>
            </div>

            <div>
              <dt className="text-xs font-semibold uppercase tracking-wide text-white/50">
                Financial advice
              </dt>

              <dd className="mt-1 text-sm text-white/75">
                This calculator does not provide personalized financial advice
                or guarantee investment performance.
              </dd>
            </div>
          </dl>
        </div>
      </section>

      {/* Disclaimer */}
      <section
        aria-labelledby="disclaimer-heading"
        className="space-y-4"
      >
        <h2
          id="disclaimer-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Investment Disclaimer
        </h2>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
          <p className="text-xs leading-7 text-white/65 sm:text-sm">
            This SIP calculator is provided for educational and planning
            purposes only. The results are estimates based on the assumptions
            entered and should not be interpreted as a guarantee of future
            investment returns or investment outcomes. Actual results can
            vary because of market performance, inflation, taxes, fees,
            investment selection, changes in contributions, and other factors.
          </p>

          <p className="mt-4 text-xs leading-7 text-white/65 sm:text-sm">
            Consider your own financial circumstances, objectives, risk
            tolerance, investment horizon, and applicable investment costs
            before making investment decisions. Where appropriate, consider
            obtaining advice from a qualified financial professional.
          </p>
        </div>
      </section>

      {/* Related Tools */}
      <RelatedTools toolId="calculator/sip-calculator" />

      {/* FAQ */}
      <section
        aria-labelledby="faq-heading"
        className="space-y-4"
      >
        <h2
          id="faq-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Frequently Asked Questions
        </h2>

        <div className="space-y-4">
          {faqItems.map((item) => (
            <div
              key={item.q}
              className="group overflow-hidden rounded-2xl border border-white/10 bg-white/5"
            >
              <details className="w-full">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 hover:bg-white/10">
                  <span className="text-sm font-semibold text-white">
                    {item.q}
                  </span>

                  <span
                    aria-hidden="true"
                    className="shrink-0 text-lg text-blue-400"
                  >
                    <svg
                      className="h-5 w-5"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </summary>

                <div className="border-t border-dashed border-white/5 p-5 pt-4">
                  <p className="text-xs leading-relaxed text-white/60">
                    {item.a}
                  </p>
                </div>
              </details>
            </div>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section
        aria-labelledby="cta-heading"
        className="rounded-3xl border border-white/10 bg-white/5 p-6 text-center sm:p-8"
      >
        <h2
          id="cta-heading"
          className="text-2xl font-semibold tracking-tight"
        >
          Calculate Your SIP Investment
        </h2>

        <p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-white/65">
          Enter your monthly investment, investment period, and expected
          return above to estimate your total investment, potential returns,
          and projected SIP maturity value. Compare different SIP scenarios
          to understand how contribution amount and investment duration can
          affect the result.
        </p>

        <p className="mt-4 text-xs text-white/45">
          Results are estimates for planning purposes and are not guaranteed
          investment outcomes.
        </p>
      </section>
    </div>
  );
}